### ISSUE TITLE
求放出android 编译版本！

### ISSUE THREAD

**Issue by lshilshi** [wenhelinlu/spark#6]
官方客户端难用

所以转战其它客户端
所幸找到大佬开发的，
我可以fork，但是用Gayhub Action自动编译打包每次都是出错

故求大佬，请放出android 编译版本！

**Comment by wenhelinlu** [comment]
你fork了最新的代码了吗？之前编译错误应该是google firebase导致的，现在的代码已经去除了，你重新编译试试。

**Comment by wenhelinlu** [comment]
你将代码down下来，使用Android Studio编译，不要使用Github的Action，我的电脑有点问题，证书验证失败，无法编译出release。
